// Fetches movie data from the TMDB API at curation time (ADR 0001) and writes:
//
//   src/data/posters.ts   — poster URLs on TMDB's CDN (replaces the Wikipedia scraper)
//   src/data/cast.ts      — top-billed cast for movies missing an entry (hand edits kept)
//   src/data/generated.ts — lists defined as TMDB queries in scripts/tmdb-lists.config.mjs
//
//   TMDB_API_KEY=... node scripts/fetch-tmdb.mjs
//
// Accepts a v3 API key or a v4 read access token (free at
// https://www.themoviedb.org/settings/api). The key can also live in a .env
// file at the repo root (gitignored); a variable set in the shell wins. Safe to re-run: posters already on
// image.tmdb.org and existing cast entries are skipped, so a run only fetches
// what's new — the first run migrates Wikipedia poster URLs. To re-fetch one
// movie, delete its lines from posters.ts / cast.ts. Misses are listed at the
// end; a movie without a poster or cast entry still works — the ticket falls
// back to text.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const MOVIES_TS = join(root, "src", "data", "movies.ts");
const POSTERS_TS = join(root, "src", "data", "posters.ts");
const CAST_TS = join(root, "src", "data", "cast.ts");
const GENERATED_TS = join(root, "src", "data", "generated.ts");

const TMDB_IMG = "https://image.tmdb.org/t/p/w500";
const DELAY_MS = 25;

try {
	process.loadEnvFile(join(root, ".env"));
} catch {
	// no .env file — rely on the shell environment
}

const TOKEN = process.env.TMDB_API_KEY;
if (!TOKEN) {
	console.error(
		"TMDB_API_KEY is not set (in the environment or a .env file at the repo root).\n" +
			"Get a free key at https://www.themoviedb.org/settings/api",
	);
	process.exit(1);
}
const isV4Token = TOKEN.startsWith("eyJ");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function tmdb(path, params = {}) {
	const url = new URL(`https://api.themoviedb.org/3${path}`);
	for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
	if (!isV4Token) url.searchParams.set("api_key", TOKEN);
	const init = isV4Token ? { headers: { Authorization: `Bearer ${TOKEN}` } } : undefined;
	for (let attempt = 0; ; attempt++) {
		const res = await fetch(url, init);
		if (res.ok) return res.json();
		if ((res.status === 429 || res.status >= 500) && attempt < 3) {
			const wait = Number(res.headers.get("retry-after")) * 1000 || 2 ** attempt * 1000;
			console.log(`  TMDB ${res.status}, backing off ${wait / 1000}s...`);
			await sleep(wait);
			continue;
		}
		throw new Error(`TMDB ${res.status} on ${path}`);
	}
}

// ---------------------------------------------------------------------------
// Reading and writing the data files

function handCuratedMovies() {
	const src = readFileSync(MOVIES_TS, "utf8");
	const seen = new Map();
	for (const match of src.matchAll(/m\(\s*(['"])(.+?)\1,\s*(\d{4}),/g)) {
		const title = match[2].replace(/\\'/g, "'");
		const year = Number(match[3]);
		seen.set(`${title}|${year}`, { title, year });
	}
	return [...seen.values()];
}

/** Parses `"Title|Year": <value>` entries regardless of how oxfmt wrapped them. */
function parseMap(file, valuePattern, parseValue) {
	const map = {};
	let src;
	try {
		src = readFileSync(file, "utf8");
	} catch {
		return map;
	}
	const entry = new RegExp(`("(?:[^"\\\\]|\\\\.)*\\|\\d{4}")\\s*:\\s*(${valuePattern})`, "g");
	for (const match of src.matchAll(entry)) {
		map[JSON.parse(match[1])] = parseValue(match[2]);
	}
	return map;
}

const existingPosters = () => parseMap(POSTERS_TS, `"(?:[^"\\\\]|\\\\.)*"`, JSON.parse);
const existingCast = () =>
	parseMap(CAST_TS, `\\[[^\\]]*\\]`, (v) => JSON.parse(v.replace(/,\s*\]/, "]")));

function writePosters(map) {
	const lines = Object.keys(map)
		.sort()
		.map((k) => `\t${JSON.stringify(k)}: ${JSON.stringify(map[k])},`);
	writeFileSync(
		POSTERS_TS,
		`// Generated by scripts/fetch-tmdb.mjs — safe to edit by hand for one-off fixes.
// Keys are \`\${title}|\${year}\` matching src/data/movies.ts.
export const POSTERS: Record<string, string> = {
${lines.join("\n")}
};
`,
	);
}

function writeCast(map) {
	const lines = Object.keys(map)
		.sort()
		.map((k) => `\t${JSON.stringify(k)}: ${JSON.stringify(map[k])},`);
	writeFileSync(
		CAST_TS,
		`// Top-billed cast for every movie, keyed by \`\${title}|\${year}\` matching movies.ts.
// Filled by scripts/fetch-tmdb.mjs; existing entries are never overwritten, so hand
// edits are safe.
export const CAST: Record<string, string[]> = {
${lines.join("\n")}
};
`,
	);
}

function writeGenerated(lists) {
	const renderMovie = (mv) =>
		`\t\t\t{ title: ${JSON.stringify(mv.title)}, year: ${mv.year}, blurb: ${JSON.stringify(mv.blurb)} },`;
	const renderList = (list) => `\t{
\t\tid: ${JSON.stringify(list.id)},
\t\tname: ${JSON.stringify(list.name)},
\t\ttagline: ${JSON.stringify(list.tagline)},
\t\tmovies: [
${list.movies.map(renderMovie).join("\n")}
\t\t],
\t},`;
	writeFileSync(
		GENERATED_TS,
		`// Generated by scripts/fetch-tmdb.mjs from scripts/tmdb-lists.config.mjs — do not
// edit; re-run the script to refresh. Posters and cast are keyed through
// posters.ts / cast.ts like every other list.
import type { MovieList } from "./movies";

export const GENERATED_LISTS: MovieList[] = [
${lists.map(renderList).join("\n")}
];
`,
	);
}

// ---------------------------------------------------------------------------
// Generate mode: lists defined as TMDB queries

/** First sentence of a TMDB overview, trimmed toward the hand-written blurb voice. */
function blurbFrom(overview = "") {
	const text = overview.trim();
	// A period after an abbreviation or an initial doesn't end the sentence
	// ("Dr. Frankenstein", "Capt. Reyes", "J. K. Rowling").
	const abbrev = /\b(?:Mr|Mrs|Ms|Dr|St|Sgt|Capt|Lt|Col|Gen|Prof|Jr|Sr|vs|[A-Z])\.$/;
	let first = text;
	for (const match of text.matchAll(/[.!?](?=\s|$)/g)) {
		const candidate = text.slice(0, match.index + 1);
		if (abbrev.test(candidate)) continue;
		first = candidate;
		break;
	}
	if (first.length > 140) first = first.slice(0, 110).replace(/\s+\S*$/, "") + "…";
	return first.replace(/\.$/, "");
}

let genresByName;
async function resolveGenres(value) {
	if (/^[\d,|]+$/.test(String(value))) return value;
	genresByName ??= new Map(
		(await tmdb("/genre/movie/list")).genres.map((g) => [g.name.toLowerCase(), g.id]),
	);
	return String(value)
		.split(/([|,])/)
		.map((part) =>
			part === "," || part === "|" ? part : (genresByName.get(part.trim().toLowerCase()) ?? part),
		)
		.join("");
}

async function generateList(def) {
	const limit = def.limit ?? 24;
	const params = { ...def.discover };
	if (params.with_genres) params.with_genres = await resolveGenres(params.with_genres);
	const results = [];
	for (let page = 1; results.length < limit && page <= 10; page++) {
		const body = def.chart
			? await tmdb(`/movie/${def.chart}`, { page })
			: await tmdb("/discover/movie", {
					include_adult: false,
					"vote_count.gte": 50,
					...params,
					page,
				});
		results.push(...(body.results ?? []).filter((r) => r.release_date && r.title));
		if (page >= body.total_pages) break;
		await sleep(DELAY_MS);
	}
	const movies = results.slice(0, limit).map((r) => ({
		title: r.title,
		year: Number(r.release_date.slice(0, 4)),
		blurb: blurbFrom(r.overview),
		tmdb: r,
	}));
	if (movies.length < 16) {
		console.warn(`WARNING: list "${def.id}" has only ${movies.length} movies — the app draws 16.`);
	}
	return { id: def.id, name: def.name, tagline: def.tagline, movies };
}

// ---------------------------------------------------------------------------
// Enrich mode: posters + cast for every movie, hand-curated or generated

async function searchMovie({ title, year }) {
	const exact = await tmdb("/search/movie", {
		query: title,
		primary_release_year: year,
		include_adult: false,
	});
	if (exact.results?.length) return exact.results[0];
	const loose = await tmdb("/search/movie", { query: title, include_adult: false });
	return (
		loose.results?.find((r) => Math.abs(Number(r.release_date?.slice(0, 4)) - year) <= 1) ?? null
	);
}

let config = [];
try {
	config = (await import("./tmdb-lists.config.mjs")).default;
} catch (err) {
	if (err.code !== "ERR_MODULE_NOT_FOUND") throw err;
}

const resolved = new Map(); // key -> TMDB search/discover result
const movies = new Map(handCuratedMovies().map((mv) => [`${mv.title}|${mv.year}`, mv]));

if (config.length) {
	console.log(`Generating ${config.length} query-defined list(s)...`);
	const lists = [];
	for (const def of config) {
		const list = await generateList(def);
		lists.push(list);
		console.log(`  ${list.id}: ${list.movies.length} movies`);
		for (const mv of list.movies) {
			const key = `${mv.title}|${mv.year}`;
			resolved.set(key, mv.tmdb);
			movies.set(key, { title: mv.title, year: mv.year });
		}
	}
	writeGenerated(lists.map((l) => ({ ...l, movies: l.movies.map(({ tmdb: _, ...mv }) => mv) })));
}

const posters = existingPosters();
const cast = existingCast();
const pending = [...movies.entries()].filter(
	([key]) => !posters[key]?.startsWith(TMDB_IMG) || !(key in cast),
);
console.log(`${movies.size} unique movies, ${pending.length} to enrich`);

const misses = [];
let done = 0;
for (const [key, movie] of pending) {
	done++;
	const hit = resolved.get(key) ?? (await searchMovie(movie));
	if (!hit) {
		misses.push(key);
		console.log(`[${done}/${pending.length}] MISS  ${key}`);
		await sleep(DELAY_MS);
		continue;
	}
	const notes = [];
	if (!posters[key]?.startsWith(TMDB_IMG)) {
		if (hit.poster_path) posters[key] = `${TMDB_IMG}${hit.poster_path}`;
		else notes.push(posters[key] ? "kept old poster" : "no poster");
	}
	if (!(key in cast)) {
		const credits = await tmdb(`/movie/${hit.id}/credits`);
		const names = (credits.cast ?? []).slice(0, 3).map((c) => c.name);
		if (names.length) cast[key] = names;
		else notes.push("no cast");
	}
	writePosters(posters);
	writeCast(cast);
	console.log(
		`[${done}/${pending.length}] ok    ${key}${notes.length ? ` (${notes.join(", ")})` : ""}`,
	);
	await sleep(DELAY_MS);
}

console.log(
	`\nDone. ${Object.keys(posters).length} posters, ${Object.keys(cast).length} cast entries, ${misses.length} unresolved.`,
);
if (misses.length) {
	console.log(
		"Unresolved on TMDB (fix by hand in posters.ts / cast.ts):\n" +
			misses.map((k) => `  - ${k}`).join("\n"),
	);
}
