// Fetches poster artwork for every movie in src/data/movies.ts from the
// Wikipedia API (no key required) and writes src/data/posters.ts.
//
//   node scripts/fetch-posters.mjs
//
// Posters are each film article's infobox image, hotlinked from
// upload.wikimedia.org. One API call per movie (all title candidates batched),
// throttled and retried politely. Safe to re-run: already-fetched movies are
// skipped, so an interrupted run resumes where it left off. Misses are listed
// at the end — paste a URL into posters.ts by hand, or leave them; the app
// falls back to a text-only ticket.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const MOVIES_TS = join(root, "src", "data", "movies.ts");
const POSTERS_TS = join(root, "src", "data", "posters.ts");

const API = "https://en.wikipedia.org/w/api.php";
const UA = "whattowatch-poster-fetch/1.0 (personal movie-bracket app)";
const DELAY_MS = 800;
const BACKOFFS_MS = [10_000, 30_000, 90_000];

// Movies whose Wikipedia article name can't be derived from title + year.
const ALIASES = {
	"Se7en|1995": "Seven (1995 film)",
	"WALL·E|2008": "WALL-E",
	"Harry Potter and the Sorcerer's Stone|2001": "Harry Potter and the Philosopher's Stone (film)",
	"Star Wars|1977": "Star Wars (film)",
	"Kill Bill: Vol. 1|2003": "Kill Bill: Volume 1",
	"Glass Onion|2022": "Glass Onion: A Knives Out Mystery",
	"Aladdin|1992": "Aladdin (1992 Disney film)",
};

function uniqueMovies() {
	const src = readFileSync(MOVIES_TS, "utf8");
	const seen = new Map();
	for (const match of src.matchAll(/m\((['"])(.+?)\1,\s*(\d{4}),/g)) {
		const title = match[2].replace(/\\'/g, "'");
		const year = Number(match[3]);
		seen.set(`${title}|${year}`, { title, year });
	}
	return [...seen.values()];
}

function existingPosters() {
	try {
		const src = readFileSync(POSTERS_TS, "utf8");
		const map = {};
		for (const match of src.matchAll(/^\s{2}(".+?"): (".+?"),$/gm)) {
			map[JSON.parse(match[1])] = JSON.parse(match[2]);
		}
		return map;
	} catch {
		return {};
	}
}

function writePosters(map) {
	const keys = Object.keys(map).sort();
	const lines = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`);
	writeFileSync(
		POSTERS_TS,
		`// Generated by scripts/fetch-posters.mjs — safe to edit by hand for one-off fixes.
// Keys are \`\${title}|\${year}\` matching src/data/movies.ts.
export const POSTERS: Record<string, string> = {
${lines.join("\n")}
}
`,
	);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** One batched query for all candidate titles, with polite retry on throttling. */
async function queryPages(titles) {
	const params = new URLSearchParams({
		action: "query",
		format: "json",
		redirects: "1",
		maxlag: "5",
		titles: titles.join("|"),
		prop: "pageimages|description|extracts",
		piprop: "original",
		pilicense: "any", // film posters are non-free; the default filters them out
		exintro: "1",
		explaintext: "1",
		exchars: "400",
	});
	for (let attempt = 0; ; attempt++) {
		try {
			const res = await fetch(`${API}?${params}`, { headers: { "User-Agent": UA } });
			if (res.ok) {
				const body = await res.json();
				if (body?.query?.pages) return body.query;
			}
		} catch {
			// fall through to backoff
		}
		if (attempt >= BACKOFFS_MS.length) return null;
		console.log(`  throttled, backing off ${BACKOFFS_MS[attempt] / 1000}s...`);
		await sleep(BACKOFFS_MS[attempt]);
	}
}

/** A candidate page counts if it's about a film from (roughly) the right year. */
function posterFrom(page, movie, candidateHadYear) {
	const text = `${page.description ?? ""} ${page.extract ?? ""}`.toLowerCase();
	if (!text.includes("film")) return null;
	const yearOk = [movie.year - 1, movie.year, movie.year + 1].some((y) => text.includes(String(y)));
	if (!yearOk && !candidateHadYear) return null;
	return page.original?.source ?? null;
}

async function fetchPoster(movie) {
	const key = `${movie.title}|${movie.year}`;
	const candidates = ALIASES[key]
		? [{ title: ALIASES[key], hadYear: true }]
		: [
				{ title: `${movie.title} (${movie.year} film)`, hadYear: true },
				{ title: `${movie.title} (film)`, hadYear: false },
				{ title: movie.title, hadYear: false },
			];
	const query = await queryPages(candidates.map((c) => c.title));
	if (!query) return null;

	// Map each requested title through normalization and redirects to its page.
	const resolve = new Map();
	for (const n of query.normalized ?? []) resolve.set(n.from, n.to);
	for (const r of query.redirects ?? []) resolve.set(r.from, r.to);
	const pagesByTitle = new Map(Object.values(query.pages).map((p) => [p.title, p]));

	for (const candidate of candidates) {
		let title = candidate.title;
		for (let hops = 0; hops < 3 && resolve.has(title); hops++) title = resolve.get(title);
		const page = pagesByTitle.get(title);
		if (!page || "missing" in page) continue;
		const poster = posterFrom(page, movie, candidate.hadYear);
		if (poster) return poster;
	}
	return null;
}

const movies = uniqueMovies();
const posters = existingPosters();
const pending = movies.filter((mv) => !(`${mv.title}|${mv.year}` in posters));
console.log(`${movies.length} unique movies, ${pending.length} to fetch`);

const misses = [];
let done = 0;
for (const movie of pending) {
	const key = `${movie.title}|${movie.year}`;
	const poster = await fetchPoster(movie);
	done++;
	if (poster) {
		posters[key] = poster;
		writePosters(posters);
		console.log(`[${done}/${pending.length}] ok    ${key}`);
	} else {
		misses.push(key);
		console.log(`[${done}/${pending.length}] MISS  ${key}`);
	}
	await sleep(DELAY_MS);
}

console.log(`\nDone. ${Object.keys(posters).length} posters, ${misses.length} misses.`);
if (misses.length) console.log("Missing:\n" + misses.map((k) => `  - ${k}`).join("\n"));
