// Generated by scripts/fetch-tmdb.mjs from scripts/tmdb-lists.config.mjs — do not
// edit; re-run the script to refresh. Posters and cast are keyed through
// posters.ts / cast.ts like every other list.
import type { MovieList } from "./movies";

export const GENERATED_LISTS: MovieList[] = [
	{
		id: "best-of-2025",
		name: "Best of 2025",
		tagline: "Last year's releases, ranked by the crowd",
		movies: [
			{
				title: "Chainsaw Man - The Movie: Reze Arc",
				year: 2025,
				blurb:
					"In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into…",
			},
			{
				title: "Counterattack",
				year: 2025,
				blurb: "When a hostage rescue mission creates a new enemy, Capt",
			},
			{
				title: "Ne Zha 2",
				year: 2025,
				blurb:
					"After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life",
			},
			{
				title: "KPop Demon Hunters",
				year: 2025,
				blurb:
					"When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to…",
			},
			{
				title: "How to Train Your Dragon",
				year: 2025,
				blurb:
					"On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands…",
			},
			{
				title: "The Shadow's Edge",
				year: 2025,
				blurb:
					"Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves",
			},
			{
				title: "Predator: Badlands",
				year: 2025,
				blurb:
					"Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a…",
			},
			{
				title: "F1",
				year: 2025,
				blurb:
					"Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young…",
			},
			{
				title: "Predator: Killer of Killers",
				year: 2025,
				blurb:
					"While three of the fiercest warriors in human history—a Viking raider, a ninja in feudal Japan, and a WWII…",
			},
			{
				title: "Rental Family",
				year: 2025,
				blurb:
					"An American actor in Tokyo struggles to find purpose until he lands an unusual gig: working for a Japanese…",
			},
			{
				title: "Hamnet",
				year: 2025,
				blurb:
					"The powerful story of love and loss that inspired the creation of Shakespeare's timeless masterpiece, Hamlet",
			},
			{
				title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
				year: 2025,
				blurb:
					"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face…",
			},
			{ title: "STRAW", year: 2025, blurb: "What will be her last straw?" },
			{
				title: "Zootopia 2",
				year: 2025,
				blurb:
					"After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves…",
			},
			{
				title: "The Gorge",
				year: 2025,
				blurb:
					"Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge",
			},
			{
				title: "The Bad Guys 2",
				year: 2025,
				blurb:
					"The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into…",
			},
			{ title: "Frankenstein", year: 2025, blurb: "Dr" },
			{
				title: "Avatar: Fire and Ash",
				year: 2025,
				blurb:
					"In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri…",
			},
			{
				title: "Nuremberg",
				year: 2025,
				blurb:
					"In postwar Germany, an American psychiatrist must determine whether Nazi prisoners are fit to go on trial for…",
			},
			{
				title: "No Other Choice",
				year: 2025,
				blurb:
					"After being laid off and humiliated by a ruthless job market, a veteran paper mill manager descends into…",
			},
			{
				title: "Sinners",
				year: 2025,
				blurb:
					"Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to…",
			},
			{
				title: "Sentimental Value",
				year: 2025,
				blurb:
					"Sisters Nora and Agnes reunite with their estranged father, the charismatic Gustav, a once-renowned director…",
			},
			{
				title: "Marty Supreme",
				year: 2025,
				blurb:
					"Marty Mauser, a young man with a dream no one respects, goes to hell and back in pursuit of greatness",
			},
			{
				title: "Our Fault",
				year: 2025,
				blurb:
					"Jenna and Lion's wedding brings about the long-awaited reunion between Noah and Nick after their breakup",
			},
		],
	},
];
