import { POSTERS } from "./posters";
import { CAST } from "./cast";
import { GENERATED_LISTS } from "./generated";

export interface Movie {
	title: string;
	year: number;
	blurb: string;
	poster?: string;
	cast?: string[];
}

export interface MovieList {
	id: string;
	name: string;
	tagline: string;
	movies: Movie[];
}

// Every lineup is grounded in a TMDB chart or discover query (ADR 0001),
// defined in scripts/tmdb-lists.config.mjs and materialized into generated.ts
// by scripts/fetch-tmdb.mjs. Lists refresh on script re-run + deploy.
export const MOVIE_LISTS: MovieList[] = [...GENERATED_LISTS];

// Posters and cast (generated by scripts/fetch-tmdb.mjs) are keyed by
// `${title}|${year}` so the list data stays clean.
for (const list of MOVIE_LISTS) {
	for (const movie of list.movies) {
		const key = `${movie.title}|${movie.year}`;
		movie.poster = POSTERS[key];
		movie.cast = CAST[key];
	}
}
