// Generated by scripts/fetch-posters.mjs — safe to edit by hand for one-off fixes.
// Keys are `${title}|${year}` matching src/data/movies.ts.
export const POSTERS: Record<string, string> = {
	"(500) Days of Summer|2009":
		"https://upload.wikimedia.org/wikipedia/en/d/d1/Five_hundred_days_of_summer.jpg",
	"10 Things I Hate About You|1999":
		"https://upload.wikimedia.org/wikipedia/en/9/95/10_Things_I_Hate_About_You_film.jpg",
	"12 Angry Men|1957":
		"https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg",
	"1917|2019": "https://upload.wikimedia.org/wikipedia/en/f/fe/1917_%282019%29_Film_Poster.jpeg",
	"2001: A Space Odyssey|1968":
		"https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png",
	"21 Jump Street|2012": "https://upload.wikimedia.org/wikipedia/en/9/93/21JumpStreetfilm.jpg",
	"28 Days Later|2002": "https://upload.wikimedia.org/wikipedia/en/e/e4/28_days_later.jpg",
	"A Clockwork Orange|1971":
		"https://upload.wikimedia.org/wikipedia/en/7/73/A_Clockwork_Orange_%281971%29.png",
	"A Nightmare on Elm Street|1984":
		"https://upload.wikimedia.org/wikipedia/en/f/fa/A_Nightmare_on_Elm_Street_%281984%29_theatrical_poster.jpg",
	"A Quiet Place|2018":
		"https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png",
	"About Time|2013":
		"https://upload.wikimedia.org/wikipedia/en/7/7c/About_Time_%282013_film%29_Poster.jpg",
	"Airplane!|1980":
		"https://upload.wikimedia.org/wikipedia/en/2/21/Airplane%21_%281980_film%29.jpg",
	"Aladdin|1992":
		"https://upload.wikimedia.org/wikipedia/en/b/bd/Aladdin_%281992_Disney_film%29_poster.jpg",
	"Aliens|1986": "https://upload.wikimedia.org/wikipedia/en/f/fb/Aliens_poster.jpg",
	"Alien|1979": "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
	"Amadeus|1984": "https://upload.wikimedia.org/wikipedia/en/2/2f/Amadeusmov.jpg",
	"American Beauty|1999":
		"https://upload.wikimedia.org/wikipedia/en/9/9a/American_Beauty_1999_film_poster.jpg",
	"Amélie|2001": "https://upload.wikimedia.org/wikipedia/en/5/53/Amelie_poster.jpg",
	"Anchorman: The Legend of Ron Burgundy|2004":
		"https://upload.wikimedia.org/wikipedia/en/6/64/Movie_poster_Anchorman_The_Legend_of_Ron_Burgundy.jpg",
	"Apocalypse Now|1979": "https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg",
	"Arrival|2016": "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg",
	"Avatar|2009": "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg",
	"Baby Driver|2017": "https://upload.wikimedia.org/wikipedia/en/8/8e/Baby_Driver_poster.jpg",
	"Back to the Future|1985":
		"https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
	"Beauty and the Beast|1991":
		"https://upload.wikimedia.org/wikipedia/en/5/5e/Beauty_and_the_Beast_%281991_film%29_poster.jpg",
	"Before Sunrise|1995": "https://upload.wikimedia.org/wikipedia/en/d/da/Before_Sunrise_poster.jpg",
	"Big|1988": "https://upload.wikimedia.org/wikipedia/en/b/be/Big_Poster.jpg",
	"Blade Runner 2049|2017":
		"https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png",
	"Blade Runner|1982":
		"https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png",
	"Blazing Saddles|1974":
		"https://upload.wikimedia.org/wikipedia/en/7/7b/Blazing_saddles_movie_poster.jpg",
	"Braveheart|1995": "https://upload.wikimedia.org/wikipedia/en/e/e1/Braveheart_film_poster.png",
	"Bridesmaids|2011": "https://upload.wikimedia.org/wikipedia/en/d/df/BridesmaidsPoster.jpg",
	"Bridget Jones's Diary|2001":
		"https://upload.wikimedia.org/wikipedia/en/1/17/BridgetJonesDiaryMoviePoster.jpg",
	"CODA|2021": "https://upload.wikimedia.org/wikipedia/en/8/89/Coda_poster.jpeg",
	"Casablanca|1942":
		"https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg",
	"Casino Royale|2006":
		"https://upload.wikimedia.org/wikipedia/en/8/82/Casino_Royale_%282006_film_poster%29.jpg",
	"Chef|2014": "https://upload.wikimedia.org/wikipedia/en/b/b8/Chef_2014.jpg",
	"Cinema Paradiso|1988": "https://upload.wikimedia.org/wikipedia/en/8/86/CinemaParadiso.jpg",
	"Citizen Kane|1941":
		"https://upload.wikimedia.org/wikipedia/commons/c/c0/Citizen_Kane_poster%2C_1941_%28Style_B%2C_unrestored%29.jpg",
	"City of God|2002": "https://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg",
	"Close Encounters of the Third Kind|1977":
		"https://upload.wikimedia.org/wikipedia/en/b/ba/Close_Encounters_of_the_Third_Kind_%281977%29_theatrical_poster.jpg",
	"Clueless|1995": "https://upload.wikimedia.org/wikipedia/en/5/5a/Clueless_film_poster.png",
	"Coco|2017": "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg",
	"Crazy Rich Asians|2018":
		"https://upload.wikimedia.org/wikipedia/en/b/ba/Crazy_Rich_Asians_poster.png",
	"Crouching Tiger, Hidden Dragon|2000":
		"https://upload.wikimedia.org/wikipedia/en/2/27/Crouching_Tiger%2C_Hidden_Dragon_%28Chinese_poster%29.png",
	"Das Boot|1981": "https://upload.wikimedia.org/wikipedia/en/a/a3/Das_boot_ver1.jpg",
	"Die Hard|1988":
		"https://upload.wikimedia.org/wikipedia/en/c/ca/Die_Hard_%281988_film%29_poster.jpg",
	"District 9|2009": "https://upload.wikimedia.org/wikipedia/en/d/d7/District_nine_ver2.jpg",
	"Django Unchained|2012":
		"https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg",
	"Dumb and Dumber|1994": "https://upload.wikimedia.org/wikipedia/en/6/64/Dumbanddumber.jpg",
	"Dune: Part Two|2024": "https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg",
	"Dune|2021": "https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg",
	"E.T. the Extra-Terrestrial|1982":
		"https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg",
	"Edge of Tomorrow|2014":
		"https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg",
	"Eternal Sunshine of the Spotless Mind|2004":
		"https://upload.wikimedia.org/wikipedia/en/a/a4/Eternal_Sunshine_of_the_Spotless_Mind.png",
	"Everything Everywhere All at Once|2022":
		"https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg",
	"Ex Machina|2014": "https://upload.wikimedia.org/wikipedia/en/b/ba/Ex-machina-uk-poster.jpg",
	"Face/Off|1997": "https://upload.wikimedia.org/wikipedia/en/1/1c/FaceOff_poster.jpg",
	"Fargo|1996": "https://upload.wikimedia.org/wikipedia/en/3/33/Fargo_%281996_movie_poster%29.jpg",
	"Ferris Bueller's Day Off|1986":
		"https://upload.wikimedia.org/wikipedia/en/9/9b/Ferris_Bueller%27s_Day_Off.jpg",
	"Fight Club|1999": "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
	"Finding Nemo|2003": "https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg",
	"Forrest Gump|1994": "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
	"Full Metal Jacket|1987":
		"https://upload.wikimedia.org/wikipedia/en/9/99/Full_Metal_Jacket_poster.jpg",
	"Game Night|2018": "https://upload.wikimedia.org/wikipedia/en/a/a4/Game_Night_%28film%29.png",
	"Get Out|2017": "https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png",
	"Ghostbusters|1984":
		"https://upload.wikimedia.org/wikipedia/en/2/2f/Ghostbusters_%281984%29_theatrical_poster.png",
	"Gladiator|2000":
		"https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png",
	"Glass Onion|2022": "https://upload.wikimedia.org/wikipedia/en/6/62/Glass_Onion_poster.jpg",
	"Gone Girl|2014": "https://upload.wikimedia.org/wikipedia/en/0/05/Gone_Girl_Poster.jpg",
	"Good Will Hunting|1997": "https://upload.wikimedia.org/wikipedia/en/5/52/Good_Will_Hunting.png",
	"Goodfellas|1990": "https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg",
	"Groundhog Day|1993":
		"https://upload.wikimedia.org/wikipedia/en/b/b1/Groundhog_Day_%28movie_poster%29.jpg",
	"Guardians of the Galaxy|2014":
		"https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg",
	"Halloween|1978":
		"https://upload.wikimedia.org/wikipedia/en/a/af/Halloween_%281978%29_theatrical_poster.jpg",
	"Harry Potter and the Sorcerer's Stone|2001":
		"https://upload.wikimedia.org/wikipedia/en/7/7a/Harry_Potter_and_the_Philosopher%27s_Stone_banner.jpg",
	"Heat|1995": "https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg",
	"Hereditary|2018": "https://upload.wikimedia.org/wikipedia/en/d/d9/Hereditary.png",
	"Her|2013": "https://upload.wikimedia.org/wikipedia/en/4/44/Her2013Poster.jpg",
	"Hidden Figures|2016":
		"https://upload.wikimedia.org/wikipedia/en/4/4f/The_official_poster_for_the_film_Hidden_Figures%2C_2016.jpg",
	"Hitch|2005": "https://upload.wikimedia.org/wikipedia/en/d/d4/Hitch_poster.JPG",
	"Home Alone|1990": "https://upload.wikimedia.org/wikipedia/en/7/76/Home_alone_poster.jpg",
	"Hot Fuzz|2007": "https://upload.wikimedia.org/wikipedia/en/c/c9/HotFuzzUKposter.jpg",
	"How to Lose a Guy in 10 Days|2003":
		"https://upload.wikimedia.org/wikipedia/en/0/07/HowToLoseAGuyimp.jpg",
	"How to Train Your Dragon|2010":
		"https://upload.wikimedia.org/wikipedia/en/9/99/How_to_Train_Your_Dragon_Poster.jpg",
	"Howl's Moving Castle|2004":
		"https://upload.wikimedia.org/wikipedia/en/a/a0/Howls-moving-castleposter.jpg",
	"Inception|2010":
		"https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
	"Independence Day|1996":
		"https://upload.wikimedia.org/wikipedia/en/b/bb/Independence_day_movieposter.jpg",
	"Indiana Jones and the Last Crusade|1989":
		"https://upload.wikimedia.org/wikipedia/en/8/8c/Indiana_Jones_and_the_Last_Crusade.png",
	"Inside Out|2015":
		"https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg",
	"Interstellar|2014":
		"https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
	"It Follows|2014": "https://upload.wikimedia.org/wikipedia/en/9/9e/It_Follows_%28poster%29.jpg",
	"It's a Wonderful Life|1946":
		"https://upload.wikimedia.org/wikipedia/commons/2/25/It%27s_a_Wonderful_Life_%281946_poster%29.jpeg",
	"It|2017": "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg",
	"John Wick|2014": "https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg",
	"Joker|2019": "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
	"Julie & Julia|2009": "https://upload.wikimedia.org/wikipedia/en/0/00/Julie_and_julia.jpg",
	"Jurassic Park|1993": "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg",
	"Kill Bill: Vol. 1|2003": "https://upload.wikimedia.org/wikipedia/en/2/2c/Kill_Bill_Volume_1.png",
	"Klaus|2019": "https://upload.wikimedia.org/wikipedia/en/2/26/Klaus_poster.jpeg",
	"Knives Out|2019": "https://upload.wikimedia.org/wikipedia/en/1/1f/Knives_Out_poster.jpeg",
	"L.A. Confidential|1997": "https://upload.wikimedia.org/wikipedia/en/d/d8/La_confidential.jpg",
	"La La Land|2016": "https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png",
	"Lawrence of Arabia|1962":
		"https://upload.wikimedia.org/wikipedia/commons/c/c5/Lawrence_of_arabia_ver3_xxlg.jpg",
	"Legally Blonde|2001":
		"https://upload.wikimedia.org/wikipedia/en/b/be/Legally_Blonde_film_poster.png",
	"Lethal Weapon|1987": "https://upload.wikimedia.org/wikipedia/en/d/d9/Lethal_weapon1.jpg",
	"Life Is Beautiful|1997": "https://upload.wikimedia.org/wikipedia/en/7/7c/Vitaebella.jpg",
	"Little Miss Sunshine|2006":
		"https://upload.wikimedia.org/wikipedia/en/1/16/Little_miss_sunshine_poster.jpg",
	"Love Actually|2003": "https://upload.wikimedia.org/wikipedia/en/e/eb/Love_Actually_movie.jpg",
	"Léon: The Professional|1994": "https://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg",
	"Mad Max: Fury Road|2015": "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg",
	"Mamma Mia!|2008":
		"https://upload.wikimedia.org/wikipedia/en/9/95/Mamma_Mia_%282008%29_US_poster.jpg",
	"Matilda|1996": "https://upload.wikimedia.org/wikipedia/en/b/b7/Matildaposter.jpg",
	"Mean Girls|2004": "https://upload.wikimedia.org/wikipedia/en/a/ac/Mean_Girls_film_poster.png",
	"Memento|2000": "https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg",
	"Men in Black|1997": "https://upload.wikimedia.org/wikipedia/en/f/fb/Men_in_Black_Poster.jpg",
	"Midsommar|2019":
		"https://upload.wikimedia.org/wikipedia/en/4/47/Midsommar_%282019_film_poster%29.png",
	"Mission: Impossible – Fallout|2018":
		"https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg",
	"Moana|2016": "https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg",
	"Modern Times|1936":
		"https://upload.wikimedia.org/wikipedia/commons/3/36/Modern_Times_poster.jpg",
	"Monsters, Inc.|2001": "https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG",
	"Monty Python and the Holy Grail|1975":
		"https://upload.wikimedia.org/wikipedia/en/0/08/Monty-Python-1975-poster.png",
	"Moonstruck|1987": "https://upload.wikimedia.org/wikipedia/en/7/7d/Chermoonstruck.jpg",
	"Mrs. Doubtfire|1993": "https://upload.wikimedia.org/wikipedia/en/5/5a/Mrs_Doubtfire.jpg",
	"My Neighbor Totoro|1988":
		"https://upload.wikimedia.org/wikipedia/en/0/02/My_Neighbor_Totoro_-_Tonari_no_Totoro_%28Movie_Poster%29.jpg",
	"Mystic River|2003": "https://upload.wikimedia.org/wikipedia/en/9/93/Mystic_River_poster.jpg",
	"Napoleon Dynamite|2004":
		"https://upload.wikimedia.org/wikipedia/en/8/87/Napoleon_dynamite_post.jpg",
	"Nightcrawler|2014": "https://upload.wikimedia.org/wikipedia/en/d/d4/Nightcrawlerfilm.jpg",
	"No Country for Old Men|2007":
		"https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg",
	"Nope|2022": "https://upload.wikimedia.org/wikipedia/en/e/e6/Nope_%28film%29_poster.jpg",
	"North by Northwest|1959":
		"https://upload.wikimedia.org/wikipedia/commons/8/83/Northbynorthwest1.jpg",
	"Notting Hill|1999": "https://upload.wikimedia.org/wikipedia/en/3/38/NottingHillRobertsGrant.jpg",
	"Office Space|1999": "https://upload.wikimedia.org/wikipedia/en/8/8e/Office_space_poster.jpg",
	"Oldboy|2003": "https://upload.wikimedia.org/wikipedia/en/6/67/Oldboykoreanposter.jpg",
	"Once Upon a Time in the West|1968":
		"https://upload.wikimedia.org/wikipedia/en/a/a2/Once_upon_a_Time_in_the_West.jpg",
	"One Flew Over the Cuckoo's Nest|1975":
		"https://upload.wikimedia.org/wikipedia/en/2/26/One_Flew_Over_the_Cuckoo%27s_Nest_poster.jpg",
	"Paddington 2|2017": "https://upload.wikimedia.org/wikipedia/en/b/b6/Paddington_2_poster.jpg",
	"Palm Springs|2020": "https://upload.wikimedia.org/wikipedia/en/c/c5/Palm_Springs_poster.jpeg",
	"Pan's Labyrinth|2006": "https://upload.wikimedia.org/wikipedia/en/6/67/Pan%27s_Labyrinth.jpg",
	"Parasite|2019": "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png",
	"Pirates of the Caribbean: The Curse of the Black Pearl|2003":
		"https://upload.wikimedia.org/wikipedia/en/8/89/Pirates_of_the_Caribbean_-_The_Curse_of_the_Black_Pearl.png",
	"Pitch Perfect|2012":
		"https://upload.wikimedia.org/wikipedia/en/b/b9/Pitch_Perfect_movie_poster.jpg",
	"Point Break|1991": "https://upload.wikimedia.org/wikipedia/en/7/7e/Pointbreaktheatrical.jpg",
	"Pretty Woman|1990": "https://upload.wikimedia.org/wikipedia/en/b/b6/Pretty_woman_movie.jpg",
	"Pride & Prejudice|2005":
		"https://upload.wikimedia.org/wikipedia/en/0/03/Prideandprejudiceposter.jpg",
	"Princess Mononoke|1997":
		"https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png",
	"Prisoners|2013": "https://upload.wikimedia.org/wikipedia/en/6/63/Prisoners2013Poster.jpg",
	"Psycho|1960":
		"https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg",
	"Pulp Fiction|1994":
		"https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
	"Raiders of the Lost Ark|1981":
		"https://upload.wikimedia.org/wikipedia/en/4/4c/Raiders_of_the_Lost_Ark.jpg",
	"Ratatouille|2007": "https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg",
	"Rear Window|1954":
		"https://upload.wikimedia.org/wikipedia/commons/3/38/Rear_Window_film_poster.jpg",
	"Requiem for a Dream|2000":
		"https://upload.wikimedia.org/wikipedia/en/9/92/Requiem_for_a_dream.jpg",
	"Reservoir Dogs|1992": "https://upload.wikimedia.org/wikipedia/en/0/01/Reservoir_Dogs.png",
	"Roman Holiday|1953":
		"https://upload.wikimedia.org/wikipedia/commons/d/d0/Roman_Holiday_%281953_poster%29.jpg",
	"Rosemary's Baby|1968":
		"https://upload.wikimedia.org/wikipedia/en/e/ef/Rosemarys_baby_poster.jpg",
	"Saving Private Ryan|1998":
		"https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg",
	"Schindler's List|1993":
		"https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
	"School of Rock|2003": "https://upload.wikimedia.org/wikipedia/en/1/11/School_of_Rock_Poster.jpg",
	"Scream|1996": "https://upload.wikimedia.org/wikipedia/en/8/86/Scream_%281996_film%29_poster.jpg",
	"Se7en|1995": "https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg",
	"Seven Samurai|1954": "https://upload.wikimedia.org/wikipedia/en/c/c8/Seven_Samurai_Poster.png",
	"Shaun of the Dead|2004":
		"https://upload.wikimedia.org/wikipedia/en/8/8d/Shaun_of_the_Dead_film_poster.jpg",
	"Shrek|2001":
		"https://upload.wikimedia.org/wikipedia/en/7/7b/Shrek_%282001_animated_feature_film%29.jpg",
	"Shutter Island|2010": "https://upload.wikimedia.org/wikipedia/en/7/76/Shutterislandposter.jpg",
	"Sicario|2015": "https://upload.wikimedia.org/wikipedia/en/4/4b/Sicario_poster.jpg",
	"Silver Linings Playbook|2012":
		"https://upload.wikimedia.org/wikipedia/en/9/9a/Silver_Linings_Playbook_Poster.jpg",
	"Sing Street|2016": "https://upload.wikimedia.org/wikipedia/en/2/2c/Sing_Street_poster.jpeg",
	"Singin' in the Rain|1952":
		"https://upload.wikimedia.org/wikipedia/commons/5/5d/Singin%27_in_the_Rain_%281952_poster%29.jpg",
	"Sinister|2012": "https://upload.wikimedia.org/wikipedia/en/f/f8/SinisterMoviePoster2012.jpg",
	"Sister Act|1992": "https://upload.wikimedia.org/wikipedia/en/a/a3/Sister_Act_film_poster.jpg",
	"Skyfall|2012": "https://upload.wikimedia.org/wikipedia/en/a/a7/Skyfall_poster.jpg",
	"Sleepless in Seattle|1993":
		"https://upload.wikimedia.org/wikipedia/en/e/e1/Sleepless_in_seattle.jpg",
	"Snatch|2000": "https://upload.wikimedia.org/wikipedia/en/a/a7/Snatch_ver4.jpg",
	"Some Like It Hot|1959":
		"https://upload.wikimedia.org/wikipedia/commons/b/b8/Some_Like_It_Hot_%281959_poster%29.png",
	"Space Jam|1996": "https://upload.wikimedia.org/wikipedia/en/1/14/Space_jam.jpg",
	"Speed|1994": "https://upload.wikimedia.org/wikipedia/en/4/45/Speed_movie_poster.jpg",
	"Spider-Man: Across the Spider-Verse|2023":
		"https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg",
	"Spider-Man: Into the Spider-Verse|2018":
		"https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png",
	"Spirited Away|2001":
		"https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png",
	"Star Wars: Return of the Jedi|1983":
		"https://upload.wikimedia.org/wikipedia/en/b/b2/ReturnOfTheJediPoster1983.jpg",
	"Star Wars: The Empire Strikes Back|1980":
		"https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg",
	"Star Wars|1977": "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
	"Stardust|2007": "https://upload.wikimedia.org/wikipedia/en/6/6f/Stardust_promo_poster.jpg",
	"Step Brothers|2008": "https://upload.wikimedia.org/wikipedia/en/d/d9/StepbrothersMP08.jpg",
	"Sunset Boulevard|1950":
		"https://upload.wikimedia.org/wikipedia/commons/1/14/Sunset_Boulevard_%281950_poster%29.jpg",
	"Superbad|2007": "https://upload.wikimedia.org/wikipedia/en/8/8b/Superbad_Poster.png",
	"Talk to Me|2022": "https://upload.wikimedia.org/wikipedia/en/e/ef/TalkToMe2022poster.jpg",
	"Taxi Driver|1976":
		"https://upload.wikimedia.org/wikipedia/en/3/33/Taxi_Driver_%281976_film_poster%29.jpg",
	"Terminator 2: Judgment Day|1991":
		"https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png",
	"The Babadook|2014": "https://upload.wikimedia.org/wikipedia/en/d/d7/The-Babadook-Poster.jpg",
	"The Big Lebowski|1998": "https://upload.wikimedia.org/wikipedia/en/3/35/Biglebowskiposter.jpg",
	"The Big Sick|2017": "https://upload.wikimedia.org/wikipedia/en/6/69/The_Big_Sick.jpg",
	"The Bourne Identity|2002":
		"https://upload.wikimedia.org/wikipedia/en/a/ae/BourneIdentityfilm.jpg",
	"The Conjuring|2013": "https://upload.wikimedia.org/wikipedia/en/8/8c/The_Conjuring_poster.jpg",
	"The Dark Knight|2008":
		"https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
	"The Departed|2006": "https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg",
	"The Devil Wears Prada|2006":
		"https://upload.wikimedia.org/wikipedia/en/e/e7/The_Devil_Wears_Prada_main_onesheet.jpg",
	"The Exorcist|1973": "https://upload.wikimedia.org/wikipedia/en/7/7b/Exorcist_ver2.jpg",
	"The Fifth Element|1997":
		"https://upload.wikimedia.org/wikipedia/en/6/65/Fifth_element_poster_%281997%29.jpg",
	"The Fugitive|1993": "https://upload.wikimedia.org/wikipedia/en/c/c7/The_Fugitive_movie.jpg",
	"The Girl with the Dragon Tattoo|2011":
		"https://upload.wikimedia.org/wikipedia/en/8/80/The_Girl_with_the_Dragon_Tattoo_Poster.jpg",
	"The Godfather Part II|1974":
		"https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg",
	"The Godfather|1972": "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
	"The Good, the Bad and the Ugly|1966":
		"https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg",
	"The Grand Budapest Hotel|2014":
		"https://upload.wikimedia.org/wikipedia/en/1/1c/The_Grand_Budapest_Hotel.png",
	"The Greatest Showman|2017":
		"https://upload.wikimedia.org/wikipedia/en/1/10/The_Greatest_Showman_poster.png",
	"The Green Mile|1999":
		"https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg",
	"The Hangover|2009": "https://upload.wikimedia.org/wikipedia/en/b/b9/Hangoverposter09.jpg",
	"The Incredibles|2004":
		"https://upload.wikimedia.org/wikipedia/en/2/27/The_Incredibles_%282004_animated_feature_film%29.jpg",
	"The Intern|2015": "https://upload.wikimedia.org/wikipedia/en/c/c9/The_Intern_Poster.jpg",
	"The Intouchables|2011": "https://upload.wikimedia.org/wikipedia/en/9/93/The_Intouchables.jpg",
	"The Iron Giant|1999": "https://upload.wikimedia.org/wikipedia/en/d/d3/The_Iron_Giant_poster.JPG",
	"The Lion King|1994": "https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg",
	"The Lives of Others|2006":
		"https://upload.wikimedia.org/wikipedia/en/9/9f/Leben_der_anderen.jpg",
	"The Lord of the Rings: The Fellowship of the Ring|2001":
		"https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg",
	"The Lord of the Rings: The Return of the King|2003":
		"https://upload.wikimedia.org/wikipedia/en/4/48/Lord_Rings_Return_King.jpg",
	"The Martian|2015": "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg",
	"The Matrix|1999": "https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png",
	"The Notebook|2004": "https://upload.wikimedia.org/wikipedia/en/8/86/Posternotebook.jpg",
	"The Parent Trap|1998": "https://upload.wikimedia.org/wikipedia/en/f/f9/Parenttrapposter.jpg",
	"The Pianist|2002": "https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg",
	"The Prestige|2006": "https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg",
	"The Princess Bride|1987": "https://upload.wikimedia.org/wikipedia/en/d/db/Princess_bride.jpg",
	"The Raid|2011": "https://upload.wikimedia.org/wikipedia/en/9/9a/The_Raid_2011_poster.jpg",
	"The Ring|2002": "https://upload.wikimedia.org/wikipedia/en/3/37/Theringpostere.jpg",
	"The Rock|1996": "https://upload.wikimedia.org/wikipedia/en/8/82/The_Rock_%28movie%29.jpg",
	"The Sandlot|1993": "https://upload.wikimedia.org/wikipedia/en/d/d4/Sandlot_poster.jpg",
	"The Secret Life of Walter Mitty|2013":
		"https://upload.wikimedia.org/wikipedia/en/f/f2/The_Secret_Life_of_Walter_Mitty_2013_poster.jpg",
	"The Shawshank Redemption|1994":
		"https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
	"The Shining|1980":
		"https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg",
	"The Silence of the Lambs|1991":
		"https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg",
	"The Sixth Sense|1999":
		"https://upload.wikimedia.org/wikipedia/en/a/a4/The_Sixth_Sense_poster.png",
	"The Sting|1973":
		"https://upload.wikimedia.org/wikipedia/commons/a/aa/The_Sting_%281973_alt_poster%29.jpeg",
	"The Texas Chain Saw Massacre|1974":
		"https://upload.wikimedia.org/wikipedia/en/a/a0/The_Texas_Chain_Saw_Massacre_%281974%29_theatrical_poster.jpg",
	"The Thing|1982": "https://upload.wikimedia.org/wikipedia/en/e/e3/The_Thing_%281982_film%29.png",
	"The Truman Show|1998": "https://upload.wikimedia.org/wikipedia/en/c/cd/Trumanshow.jpg",
	"The Usual Suspects|1995":
		"https://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg",
	"The Witch|2015": "https://upload.wikimedia.org/wikipedia/en/b/bf/The_Witch_poster.png",
	"There Will Be Blood|2007":
		"https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg",
	"Titanic|1997":
		"https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png",
	"To Kill a Mockingbird|1962":
		"https://upload.wikimedia.org/wikipedia/commons/2/2f/To_Kill_a_Mockingbird_%281963_US_theatrical_poster%29.jpg",
	"Top Gun: Maverick|2022":
		"https://upload.wikimedia.org/wikipedia/en/1/13/Top_Gun_Maverick_Poster.jpg",
	"Toy Story|1995": "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
	"Tropic Thunder|2008": "https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg",
	"Twister|1996": "https://upload.wikimedia.org/wikipedia/en/a/a5/Twistermovieposter.jpg",
	"Up|2009": "https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg",
	"Us|2019": "https://upload.wikimedia.org/wikipedia/en/0/00/Us_%282019%29_theatrical_poster.png",
	"Vertigo|1958":
		"https://upload.wikimedia.org/wikipedia/commons/7/75/Vertigomovie_restoration.jpg",
	"WALL·E|2008": "https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg",
	"Wayne's World|1992": "https://upload.wikimedia.org/wikipedia/en/e/e0/Wayne%27s_World.jpg",
	"Wedding Crashers|2005":
		"https://upload.wikimedia.org/wikipedia/en/3/3e/Wedding_crashers_poster.jpg",
	"When Harry Met Sally...|1989":
		"https://upload.wikimedia.org/wikipedia/en/1/1c/WhenHarryMetSallyPoster.jpg",
	"Whiplash|2014": "https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg",
	"Wind River|2017":
		"https://upload.wikimedia.org/wikipedia/en/2/2e/Wind_River_%282017_film%29.png",
	"You've Got Mail|1998": "https://upload.wikimedia.org/wikipedia/en/e/ee/You%27ve_Got_Mail.jpg",
	"Zodiac|2007": "https://upload.wikimedia.org/wikipedia/en/3/3a/Zodiac2007Poster.jpg",
	"Zoolander|2001": "https://upload.wikimedia.org/wikipedia/en/7/7c/Movie_poster_zoolander.jpg",
	"Zootopia|2016": "https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg",
};
